### ISSUE TITLE
Test TLV_61_SubMgmtCPEIPv6PrefixList does not work on ARMv7hl

### ISSUE THREAD

**Issue by rapgro** [rlaager/docsis#12] opened 2015-03-01 19:42 UTC
I get a segmentation fault for execution of the test TLV_61_SubMgmtCPEIPv6PrefixList on ARMv7hl.

**Comment by AdrianSimionov** [comment] 2015-03-01 20:17
I do not know if I own such a hardware, can you please give me some details about the hardware and Operating System? I would like to try to reproduce this issue.

**Comment by rapgro** [comment] 2015-03-02 13:22
Please tell me how to get a full debug log that could be of any use for you.

Honestly, I do not know what Fedora Koji is using for the ARM builds. I do not have any ARM locally to test with, so have to upload the stuff each time to Fedora's build infrastructure.

**Comment by AdrianSimionov** [comment] 2015-03-02 13:27
Can you get at least the output of:
uname -a

**Comment by AdrianSimionov** [comment] 2015-03-02 13:55
I spoke with Fedora developers on IRC, it should be an ARMv7 processor, I will give it a try on an ARMv6 first as I already have the hardware.

If I cannot reproduce the issue, I will see later where I can find an ARMv7 processor.

This will take some time to be investigated.

**Comment by rapgro** [comment] 2015-03-02 14:41
http://koji.fedoraproject.org/koji/watchlogs?taskID=911946

**Comment by AdrianSimionov** [comment] 2015-03-08 23:32
I do not expect fixing this issue anytime soon. I think it would be better to just disable the failing test and continue with pushing the code to Fedora. I would keep the issue open until we find a resolution.

The code is finished for MULPI 3.0 spec and I will not start adding the 3.1 features now as I do not have the hardware to test it.

**Comment by rapgro** [comment] 2015-03-29 16:56
Take a look to the following links how to virtualize ARM systems, maybe this helps to reproduce.

http://xecdesign.com/qemu-emulating-raspberry-pi-the-easy-way/
https://fedoraproject.org/wiki/Architectures/ARM/HowToQemu

**Comment by rapgro** [comment] 2015-03-29 16:59
Also, another test (which name I do not remember) fails for PPC build. PPC is secondary for Fedora, so this issue is not important.

**Comment by AdrianSimionov** [comment] 2015-03-29 21:30
I tried QEMU but I ended up with an ARMv6 system. I was not able to emulate in QEMU an ARMv7.

The new Raspberry PI has an ARMv7 CPU.

**Comment by AdrianSimionov** [comment] 2015-05-17 11:40
I was able to reproduce this issue, it looks like a bug on ARMv7 architecture.

**Comment by AdrianSimionov** [comment] 2015-05-20 14:06
@rapgro let me know if the ARM issue is also fixed for Fedora whenever you have time. I tested it on Debian 8 only under ARMv8 and looks OK.

You also mentioned about a test failing under PPC architecture, can you please let me know exactly which test?

**Comment by AdrianSimionov** [comment] 2015-05-21 21:32
All test were run under powerpc and arm64, none failed.

Closing.

**Closed by AdrianSimionov** 2015-05-21 21:32 UTC
Labels: Bug
